### ISSUE TITLE
0.3.0 Update is breaking our production branch

### ISSUE THREAD

**Issue by Kvirk** [epoberezkin/json-schema-traverse#1]
npm ERR! notarget No compatible version found: json-schema-traverse@^0.3.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.1.0, 0.0.1

├─┬ extract-text-webpack-plugin@2.1.0
│ └── ajv@4.11.7 

Seems to build now..

**Comment by epoberezkin** [comment]
did you understand what it was? I had the same issue on travis but only with node8/npm5

**Comment by Kvirk** [comment]
Since it fixed itself, it was, I think (not 100% sure), because ajv was requiring  json-schema-traverse 0.3.0 as a minimum and npm was taking its time to start serving the latest version. Hence, why npm couldn't find the 0.3.0 version.

**Comment by scottrice10** [comment]
Also seeing this issue with node -v v6.9.1 and npm -v 3.10.8.
```
Scott:rewards-ui scottrice$ npm install
npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: json-schema-traverse@0.3.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.1.0, 0.0.1
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'rewards-ui'
npm ERR! notarget

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/scottrice/code/rewards-ui/npm-debug.log
```

**Comment by epoberezkin** [comment]
It should be reported to npm, that's not the issue of this package

**Comment by scottrice10** [comment]
Per https://docs.npmjs.com/files/package-lock.json, the version of package-lock should be the same as the version in package.json. 

Haven't verified that what's causing our issues, but something to look into.

**Comment by scottrice10** [comment]
Thanks! By specifically setting "json-schema-traverse": "^0.3.1" in our package.json, the flow works now without error. Appreciate your quick response.

Agreed it's disappointing that the error message doesn't mention anything about the package-lock.json being the culprit. Certainly difficult to debug.
