### ISSUE TITLE
post-order traversal

### ISSUE THREAD

**Issue by jwalton** [epoberezkin/json-schema-traverse#3]
Hi!  I'm working on a PR to support both pre- and post-order traversal (i.e. calling `cb` before calling into children like today, and calling into it afterwards, or perhaps calling one function before and a different function afterwards.)

So I guess the first question is, are you interested in such a PR?  :)

Second; at first, I thought, "I'll just make it so you can all `traverse(schema, cb)` and it will do pre-order like today, and I'll make it so if you call `traverse(schema, {pre, post})` then it will call pre and/or post depending on which are provided."

But then I realized the optional `opts` makes this slightly more complicated.  If you provide opts, should you call `traverse(schema, {allKeys: true}, {pre, post})`?  Or should it be `traverse(schema, {allKeys: true, pre, post})` and not provide a `cb` at all?  Or maybe I'm going about this wrong and it should really be `traverse(schema, pre, post)` or `traverse(schema, opts, pre, post)`.

Since this is your baby, I figured I'd check in and see if you had a preference before I submitted a PR.  :)

**Comment by epoberezkin** [comment]
Thank you, @jwalton 

It's probably useful, is the use case to call cb after the children are modified somehow?

I think the best approach is to have all callbacks inside options, in one property, and for backwards compatibility still support the 3rd parameter as callback:

```
traverse(schema, cb); // function instead of options
traverse(schema, {allKeys: true}, cb); // backwards compatible, possibly, can be deprecated
traverse(schema, {allKeys: true, cb: {pre, post}}); // map of functions, easy to extend
traverse(schema, {allKeys: true, cb: func}); // single function (pre)
```

**Comment by jwalton** [comment]
Yeah.  I'm working on implementing OpenAPI 3.0.  They do a lot of defaults and decisions based on the "type" of a property, as defined by it's schema.  If the schema has, say, `{type: 'object', ...}` then this is easy to work out.  If the schema has bunch of `allOf`s and `oneOf`s, there will be some work involved in working out the possible set of types the schema can represent.  So at the moment I'm thinking I want to work out the "type" of each child, and then in the parent I can use the information I computed in each child to try to work out the type of the parent.  Circular refs are potentially going to be a problem...

But, getting back to this PR; would you rather:

```
traverse(schema, {allKeys: true, cb: {pre, post}});
```

Or just:

```
traverse(schema, {allKeys: true, pre, post});
```

where either pre or post can be `undefined` or a function?

Also, I know something similar was discussed in #2, but what do you think about making it so if `pre()` returns false, we don't don't traverse "this subtree"?  In my particular use case, I'm interested in:

* If I know the type of this object, I don't need to traverse any further down this subtree, but I still want to traverse sibling subtrees, so I don't want to just throw an exception and stop.
* If I find a JSON object I've already seen before, it means I have a JSON object with circular references, and I'd like to not blow up my stack.  :P  But tracking every JSON object seen before is maybe too heavyweight to put into this library (especially because I can do it with an ES6 `Set` in my use case where I know I'm running in node.js, and at the moment `json-schema-traverse` has no external dependencies and I don't want to add a Set polyfill or something).

**Comment by jwalton** [comment]
(Also also, I'd like to add a .d.ts file to this library, but I'll do that in another PR.  :)

**Comment by epoberezkin** [comment]
About the api, it’s the first - see the examples I posted above. They all need to be supported.

Other two things deserve separate issues, let’s not clutter this one.

**Comment by epoberezkin** [comment]
Or was it one thing? :)

**Comment by jwalton** [comment]
No, I can do it as different issues.  :)
